version: '3'
services:
  watcher:
    image: eth-base
    restart: always
    entrypoint: node BlockchainWatcher/watcher.js
  uport-service:
    image: eth-base
    restart: always
    entrypoint: node UportWebApp/uport.js
 
